#ifndef VCRTOS_UNITTEST_CONFIG_H
#define VCRTOS_UNITTEST_CONFIG_H

#define VCRTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 1

#define VCRTOS_CONFIG_THREAD_FLAGS_ENABLE 1
#define VCRTOS_CONFIG_THREAD_EVENT_ENABLE 1

#endif /* VCRTOS_UNITTEST_CONFIG_H */
