#ifndef VCRTOS_PROJECT_CONFIG_H
#define VCRTOS_PROJECT_CONFIG_H

#define VCRTOS_CONFIG_PLATFORM_LINUX 1

#define VCRTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0

#define VCRTOS_CONFIG_THREAD_FLAGS_ENABLE 0
#define VCRTOS_CONFIG_THREAD_EVENT_ENABLE 0

#define VCRTOS_CONFIG_MAIN_THREAD_STACK_SIZE 4096
#define VCRTOS_CONFIG_IDLE_THREAD_STACK_SIZE 4096
#define VCRTOS_CONFIG_CLI_UART_THREAD_STACK_SIZE 4096

#endif /* VCRTOS_PROJECT_CONFIG_H */
