#ifndef MTOS_DEFAULT_CONFIG_H
#define MTOS_DEFAULT_CONFIG_H

#ifndef MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE
#define MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0
#endif

#ifndef MTOS_CONFIG_THREAD_PRIORITY_LEVELS
#define MTOS_CONFIG_THREAD_PRIORITY_LEVELS 16
#endif

#endif /* MTOS_DEFAULT_CONFIG_H */
