#ifndef VCRTOS_DEFAULT_CONFIG_H
#define VCRTOS_DEFAULT_CONFIG_H

#ifndef VCRTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE
#define VCRTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0
#endif

#ifndef VCRTOS_CONFIG_THREAD_PRIORITY_LEVELS
#define VCRTOS_CONFIG_THREAD_PRIORITY_LEVELS 16
#endif

#ifndef VCRTOS_CONFIG_THREAD_FLAGS_ENABLE
#define VCRTOS_CONFIG_THREAD_FLAGS_ENABLE 0
#endif

#ifndef VCRTOS_CONFIG_THREAD_EVENT_ENABLE
#define VCRTOS_CONFIG_THREAD_EVENT_ENABLE 0
#endif

#endif /* VCRTOS_DEFAULT_CONFIG_H */
