#ifndef VCRTOS_PROJECT_CONFIG_H
#define VCRTOS_PROJECT_CONFIG_H

#define VCRTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0

#define VCRTOS_CONFIG_THREAD_FLAGS_ENABLE 1
#define VCRTOS_CONFIG_THREAD_EVENT_ENABLE 1

#define VCRTOS_CONFIG_XTIMER_DEV 0
#define VCRTOS_CONFIG_XTIMER_CHAN 0
#define VCRTOS_CONFIG_XTIMER_HZ (1000000)
#define VCRTOS_CONFIG_XTIMER_WIDTH 16

#endif /* VCRTOS_PROJECT_CONFIG_H */
