include(autogen.cmake)

if ("${CMAKE_TOOLCHAIN_FILE}" STREQUAL "")
    set(VCSOFTWARE_TOOLCHAIN_FILE ${CMAKE_SOURCE_DIR}/platform/Toolchain/${VCSOFTWARE_TOOLCHAIN}/${VCSOFTWARE_TOOLCHAIN}.cmake)
    if(EXISTS ${VCSOFTWARE_TOOLCHAIN_FILE})
        set(CMAKE_TOOLCHAIN_FILE ${VCSOFTWARE_TOOLCHAIN_FILE})
        message(STATUS "cmake file found for Toolchain in ${VCSOFTWARE_TOOLCHAIN_FILE}")
    else()
        message(STATUS "No cmake file found for Toolchain in ${VCSOFTWARE_TOOLCHAIN_FILE}")
    endif()
else()
        message(STATUS "Toolchain file was set manualy!")
endif()
include(${CMAKE_TOOLCHAIN_FILE})

set(CMAKE_DEVICE_PATH ${CMAKE_SOURCE_DIR}/platform/Device/${VCSOFTWARE_DEVICE}/${VCSOFTWARE_DEVICE}.cmake)
if(EXISTS ${CMAKE_DEVICE_PATH})
        include(${CMAKE_DEVICE_PATH})
        message(STATUS "cmake file found for Device in ${CMAKE_DEVICE_PATH}")
else()
        message(STATUS "No cmake file found for Device in ${CMAKE_DEVICE_PATH}")
endif()


set(CMAKE_OS_PATH ${CMAKE_SOURCE_DIR}/platform/OS/${VCSOFTWARE_OS}/${VCSOFTWARE_OS}.cmake)
if(EXISTS ${CMAKE_OS_PATH})
        include( ${CMAKE_OS_PATH})
        message(STATUS "cmake file found for os in  ${CMAKE_OS_PATH}")
else()
        message(STATUS "No cmake file found for os in  ${CMAKE_OS_PATH}")
endif()

message(STATUS "VCSOFTWARE_NATIVE_SDK=${VCSOFTWARE_NATIVE_SDK}")
if ("${VCSOFTWARE_NATIVE_SDK}" STREQUAL "True")
    set(CMAKE_SDK_PATH ${CMAKE_SOURCE_DIR}/${VCSOFTWARE_SDK}.cmake)
else()
    set(CMAKE_SDK_PATH ${CMAKE_SOURCE_DIR}/platform/SDK/${VCSOFTWARE_SDK}/${VCSOFTWARE_SDK}.cmake)
endif()
if(EXISTS ${CMAKE_SDK_PATH})
        include(${CMAKE_SDK_PATH})
        message(STATUS "cmake file found for sdk in  ${CMAKE_SDK_PATH}")
else()
        message(STATUS "No cmake file found for sdk in  ${CMAKE_SDK_PATH}")
endif()

foreach(MW ${VCSOFTWARE_MIDDLEWARE})
if ("${VCSOFTWARE_NATIVE_SDK}" STREQUAL "True")
    set(CMAKE_MW_PATH ${CMAKE_SOURCE_DIR}/../../../../middleware/${MW}/${MW}.cmake)
else()
    set(CMAKE_MW_PATH ${CMAKE_SOURCE_DIR}/platform/Middleware/${MW}/${MW}.cmake)
endif()
if(EXISTS ${CMAKE_MW_PATH})
        include(${CMAKE_MW_PATH})
        message(STATUS "cmake file found for Middleware in ${CMAKE_MW_PATH}")
else()
        message(STATUS "No cmake file found for Middleware in ${CMAKE_MW_PATH}")
endif()
endforeach(MW MBED_CLOUD_PLATFORM_MW)
