#ifndef MTOS_CORE_DEFAULT_CONFIG_H
#define MTOS_CORE_DEFAULT_CONFIG_H

#ifndef MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE
#define MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0
#endif

#endif /* MTOS_CORE_DEFAULT_CONFIG_H */
