#ifndef VCOS_DEFAULT_CONFIG_H
#define VCOS_DEFAULT_CONFIG_H

#ifndef VCOS_CONFIG_MULTIPLE_INSTANCE_ENABLE
#define VCOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0
#endif

#ifndef VCOS_CONFIG_THREAD_PRIORITY_LEVELS
#define VCOS_CONFIG_THREAD_PRIORITY_LEVELS 16
#endif

#ifndef VCOS_CONFIG_THREAD_FLAGS_ENABLE
#define VCOS_CONFIG_THREAD_FLAGS_ENABLE 0
#endif

#ifndef VCOS_CONFIG_THREAD_EVENT_ENABLE
#define VCOS_CONFIG_THREAD_EVENT_ENABLE 0
#endif

#endif /* VCOS_DEFAULT_CONFIG_H */
