#ifndef CORE_DEFAULT_CONFIG_H
#define CORE_DEFAULT_CONFIG_H

#ifndef MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE
#define MTOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 0
#endif

#ifndef MTOS_CONFIG_THREAD_SCHED_PRIO_LEVELS
#define MTOS_CONFIG_THREAD_SCHED_PRIO_LEVELS 16
#endif

#endif /* CORE_DEFAULT_CONFIG_H */
