#ifndef VCOS_UNITTEST_CONFIG_H
#define VCOS_UNITTEST_CONFIG_H

#define VCOS_CONFIG_MULTIPLE_INSTANCE_ENABLE 1

#define VCOS_CONFIG_THREAD_FLAGS_ENABLE 1
#define VCOS_CONFIG_THREAD_EVENT_ENABLE 1

#endif /* VCOS_UNITTEST_CONFIG_H */
